FuchsiaCity_MapScripts::
	.byte 0

FuchsiaCity_EventScript_CitySign::
	msgbox FuchsiaCity_Text_Sign1, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_SafariZoneSign::
	msgbox FuchsiaCity_Text_Sign2, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_GymSign::
	msgbox FuchsiaCity_Text_Sign3, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_WardensHomeSign::
	msgbox FuchsiaCity_Text_Sign4, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_VoltorbSign::
	msgbox FuchsiaCity_Text_Sign5, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_SlowpokeSign::
	msgbox FuchsiaCity_Text_Sign6, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_ChanseySign::
	msgbox FuchsiaCity_Text_Sign7, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_KangaskhanSign::
	msgbox FuchsiaCity_Text_Sign8, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_FossilMonSign::
	msgbox FuchsiaCity_Text_Sign9, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_LaprasSign::
	msgbox FuchsiaCity_Text_Sign10, MSGBOX_SIGN
	end

FuchsiaCity_EventScript_SafariGameSign::
	msgbox FuchsiaCity_Text_Sign11, MSGBOX_SIGN
	end

FuchsiaCity_Text_Sign1:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign2:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign3:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign4:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign5:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign6:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign7:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign8:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign9:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign10:
	.string "FuchsiaCity"

FuchsiaCity_Text_Sign11:
	.string "FuchsiaCity"

