#ifndef GUARD_CONSTANTS_MULTI_REGION_VARS_H
#define GUARD_CONSTANTS_MULTI_REGION_VARS_H

// Automatically generated by tools/gen/gba/gen_flags_vars.py. Do not edit directly.

#define VAR_CURRENT_REGION                       0x5000 // [system] 0: Hoenn, 1: Kanto, 2: Johto, 3: Sinnoh
#define VAR_TOTAL_BADGES                         0x5001 // [system] Total badges accumulated across all 4 regions (0 to 32) for battle scaling
#define VAR_HOENN_BADGES                         0x5002 // [hoenn] Hoenn gym badges obtained (0 to 8)
#define VAR_KANTO_BADGES                         0x5003 // [kanto] Kanto gym badges obtained (0 to 8)
#define VAR_JOHTO_BADGES                         0x5004 // [johto] Johto gym badges obtained (0 to 8)
#define VAR_SINNOH_BADGES                        0x5005 // [sinnoh] Sinnoh gym badges obtained (0 to 8)

#endif // GUARD_CONSTANTS_MULTI_REGION_VARS_H
