#ifndef GUARD_CONSTANTS_MULTI_REGION_FLAGS_H
#define GUARD_CONSTANTS_MULTI_REGION_FLAGS_H

// Automatically generated by tools/gen/gba/gen_flags_vars.py. Do not edit directly.

#define FLAG_SYS_MULTI_REGION_ACTIVE             0x1000 // [system] Indicates multi-region save structure is active
#define FLAG_SYS_BATTLE_SCALING_ENABLED          0x1001 // [system] Enables dynamic badge-based trainer level scaling
#define FLAG_TRANSIT_SS_TIDAL_UNLOCKED           0x1002 // [transit] Player has obtained ferry ticket for Hoenn-Kanto transit
#define FLAG_TRANSIT_MAGNET_TRAIN_UNLOCKED       0x1003 // [transit] Player has restored power to Magnet Train for Kanto-Johto transit
#define FLAG_HOENN_INTRO_COMPLETE                0x1004 // [hoenn] Completed Littleroot Town intro sequence
#define FLAG_HOENN_STARTER_CHOSEN                0x1005 // [hoenn] Rescued Professor Birch and selected starter Pokemon

#endif // GUARD_CONSTANTS_MULTI_REGION_FLAGS_H
