#ifndef GUARD_CONSTANTS_OPPONENTS_MULTI_REGION_H
#define GUARD_CONSTANTS_OPPONENTS_MULTI_REGION_H

#define TRAINERS_MULTI_REGION_START 855

// Johto Gym Leaders
#define TRAINER_LEADER_FALKNER                  (TRAINERS_MULTI_REGION_START + 0)
#define TRAINER_LEADER_FALKNER_REMATCH          (TRAINERS_MULTI_REGION_START + 1)
#define TRAINER_LEADER_BUGSY                    (TRAINERS_MULTI_REGION_START + 2)
#define TRAINER_LEADER_BUGSY_REMATCH            (TRAINERS_MULTI_REGION_START + 3)
#define TRAINER_LEADER_WHITNEY                  (TRAINERS_MULTI_REGION_START + 4)
#define TRAINER_LEADER_WHITNEY_REMATCH          (TRAINERS_MULTI_REGION_START + 5)
#define TRAINER_LEADER_MORTY                    (TRAINERS_MULTI_REGION_START + 6)
#define TRAINER_LEADER_MORTY_REMATCH            (TRAINERS_MULTI_REGION_START + 7)
#define TRAINER_LEADER_CHUCK                    (TRAINERS_MULTI_REGION_START + 8)
#define TRAINER_LEADER_CHUCK_REMATCH            (TRAINERS_MULTI_REGION_START + 9)
#define TRAINER_LEADER_JASMINE                  (TRAINERS_MULTI_REGION_START + 10)
#define TRAINER_LEADER_JASMINE_REMATCH          (TRAINERS_MULTI_REGION_START + 11)
#define TRAINER_LEADER_PRYCE                    (TRAINERS_MULTI_REGION_START + 12)
#define TRAINER_LEADER_PRYCE_REMATCH            (TRAINERS_MULTI_REGION_START + 13)
#define TRAINER_LEADER_CLAIR                    (TRAINERS_MULTI_REGION_START + 14)
#define TRAINER_LEADER_CLAIR_REMATCH            (TRAINERS_MULTI_REGION_START + 15)

// Kanto Gym Leader Rematches
#define TRAINER_LEADER_BROCK_REMATCH            (TRAINERS_MULTI_REGION_START + 16)
#define TRAINER_LEADER_MISTY_REMATCH            (TRAINERS_MULTI_REGION_START + 17)
#define TRAINER_LEADER_LT_SURGE_REMATCH         (TRAINERS_MULTI_REGION_START + 18)
#define TRAINER_LEADER_ERIKA_REMATCH            (TRAINERS_MULTI_REGION_START + 19)
#define TRAINER_LEADER_KOGA_REMATCH             (TRAINERS_MULTI_REGION_START + 20)
#define TRAINER_LEADER_SABRINA_REMATCH          (TRAINERS_MULTI_REGION_START + 21)
#define TRAINER_LEADER_BLAINE_REMATCH           (TRAINERS_MULTI_REGION_START + 22)
#define TRAINER_LEADER_GIOVANNI_REMATCH         (TRAINERS_MULTI_REGION_START + 23)

// Sinnoh Gym Leaders
#define TRAINER_LEADER_ROARK                    (TRAINERS_MULTI_REGION_START + 24)
#define TRAINER_LEADER_ROARK_REMATCH            (TRAINERS_MULTI_REGION_START + 25)
#define TRAINER_LEADER_GARDENIA                 (TRAINERS_MULTI_REGION_START + 26)
#define TRAINER_LEADER_GARDENIA_REMATCH         (TRAINERS_MULTI_REGION_START + 27)
#define TRAINER_LEADER_MAYLENE                  (TRAINERS_MULTI_REGION_START + 28)
#define TRAINER_LEADER_MAYLENE_REMATCH          (TRAINERS_MULTI_REGION_START + 29)
#define TRAINER_LEADER_CRASHER_WAKE             (TRAINERS_MULTI_REGION_START + 30)
#define TRAINER_LEADER_CRASHER_WAKE_REMATCH     (TRAINERS_MULTI_REGION_START + 31)
#define TRAINER_LEADER_FANTINA                  (TRAINERS_MULTI_REGION_START + 32)
#define TRAINER_LEADER_FANTINA_REMATCH          (TRAINERS_MULTI_REGION_START + 33)
#define TRAINER_LEADER_BYRON                    (TRAINERS_MULTI_REGION_START + 34)
#define TRAINER_LEADER_BYRON_REMATCH            (TRAINERS_MULTI_REGION_START + 35)
#define TRAINER_LEADER_CANDICE                  (TRAINERS_MULTI_REGION_START + 36)
#define TRAINER_LEADER_CANDICE_REMATCH          (TRAINERS_MULTI_REGION_START + 37)
#define TRAINER_LEADER_VOLKNER                  (TRAINERS_MULTI_REGION_START + 38)
#define TRAINER_LEADER_VOLKNER_REMATCH          (TRAINERS_MULTI_REGION_START + 39)

// Multi-Region Champions & Post-Game Rematches
#define TRAINER_CHAMPION_BLUE_REMATCH           (TRAINERS_MULTI_REGION_START + 40)
#define TRAINER_CHAMPION_LANCE_REMATCH          (TRAINERS_MULTI_REGION_START + 41)
#define TRAINER_CHAMPION_CYNTHIA_REMATCH        (TRAINERS_MULTI_REGION_START + 42)
#define TRAINER_CHAMPION_WALLACE_REMATCH        (TRAINERS_MULTI_REGION_START + 43)
#define TRAINER_CHAMPION_STEVEN_REMATCH         (TRAINERS_MULTI_REGION_START + 44)
#define TRAINER_CHAMPION_RED_POSTGAME           (TRAINERS_MULTI_REGION_START + 45)

#define TRAINERS_MULTI_REGION_COUNT             46

#endif // GUARD_CONSTANTS_OPPONENTS_MULTI_REGION_H
