LavenderTown_MapScripts::
	.byte 0

LavenderTown_EventScript_SilphScopeNotice::
	msgbox LavenderTown_Text_Sign1, MSGBOX_SIGN
	end

LavenderTown_EventScript_TownSign::
	msgbox LavenderTown_Text_Sign2, MSGBOX_SIGN
	end

LavenderTown_EventScript_PokemonTowerSign::
	msgbox LavenderTown_Text_Sign3, MSGBOX_SIGN
	end

LavenderTown_EventScript_VolunteerHouseSign::
	msgbox LavenderTown_Text_Sign4, MSGBOX_SIGN
	end

LavenderTown_Text_Sign1:
	.string "LavenderTown"

LavenderTown_Text_Sign2:
	.string "LavenderTown"

LavenderTown_Text_Sign3:
	.string "LavenderTown"

LavenderTown_Text_Sign4:
	.string "LavenderTown"

