Route17_MapScripts::
	.byte 0

Route17_EventScript_RouteSign::
	msgbox Route17_Text_Sign1, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips2::
	msgbox Route17_Text_Sign2, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips1::
	msgbox Route17_Text_Sign3, MSGBOX_SIGN
	end

Route17_EventScript_ItemsNotice::
	msgbox Route17_Text_Sign4, MSGBOX_SIGN
	end

Route17_EventScript_BallsNotice::
	msgbox Route17_Text_Sign5, MSGBOX_SIGN
	end

Route17_EventScript_CyclingRoadSign::
	msgbox Route17_Text_Sign6, MSGBOX_SIGN
	end

Route17_Text_Sign1:
	.string "Route17"

Route17_Text_Sign2:
	.string "Route17"

Route17_Text_Sign3:
	.string "Route17"

Route17_Text_Sign4:
	.string "Route17"

Route17_Text_Sign5:
	.string "Route17"

Route17_Text_Sign6:
	.string "Route17"

