VermilionCity_MapScripts::
	.byte 0

VermilionCity_EventScript_CitySign::
	msgbox VermilionCity_Text_Sign1, MSGBOX_SIGN
	end

VermilionCity_EventScript_PokemonFanClubSign::
	msgbox VermilionCity_Text_Sign2, MSGBOX_SIGN
	end

VermilionCity_EventScript_GymSign::
	msgbox VermilionCity_Text_Sign3, MSGBOX_SIGN
	end

VermilionCity_EventScript_HarborSign::
	msgbox VermilionCity_Text_Sign4, MSGBOX_SIGN
	end

VermilionCity_EventScript_SnorlaxNotice::
	msgbox VermilionCity_Text_Sign5, MSGBOX_SIGN
	end

VermilionCity_Text_Sign1:
	.string "VermilionCity"

VermilionCity_Text_Sign2:
	.string "VermilionCity"

VermilionCity_Text_Sign3:
	.string "VermilionCity"

VermilionCity_Text_Sign4:
	.string "VermilionCity"

VermilionCity_Text_Sign5:
	.string "VermilionCity"

