CinnabarIsland_MapScripts::
	.byte 0

CinnabarIsland_EventScript_IslandSign::
	msgbox CinnabarIsland_Text_Sign1, MSGBOX_SIGN
	end

CinnabarIsland_EventScript_PokemonLabSign::
	msgbox CinnabarIsland_Text_Sign2, MSGBOX_SIGN
	end

CinnabarIsland_EventScript_GymSign::
	msgbox CinnabarIsland_Text_Sign3, MSGBOX_SIGN
	end

CinnabarIsland_EventScript_PokemonLabSign::
	msgbox CinnabarIsland_Text_Sign4, MSGBOX_SIGN
	end

CinnabarIsland_Text_Sign1:
	.string "CinnabarIsland"

CinnabarIsland_Text_Sign2:
	.string "CinnabarIsland"

CinnabarIsland_Text_Sign3:
	.string "CinnabarIsland"

CinnabarIsland_Text_Sign4:
	.string "CinnabarIsland"

