SaffronCity_MapScripts::
	.byte 0

SaffronCity_EventScript_CitySign::
	msgbox SaffronCity_Text_Sign1, MSGBOX_SIGN
	end

SaffronCity_EventScript_DojoSign::
	msgbox SaffronCity_Text_Sign2, MSGBOX_SIGN
	end

SaffronCity_EventScript_SilphProductSign::
	msgbox SaffronCity_Text_Sign3, MSGBOX_SIGN
	end

SaffronCity_EventScript_TrainerTips2::
	msgbox SaffronCity_Text_Sign4, MSGBOX_SIGN
	end

SaffronCity_EventScript_SilphCoSign::
	msgbox SaffronCity_Text_Sign5, MSGBOX_SIGN
	end

SaffronCity_EventScript_TrainerTips1::
	msgbox SaffronCity_Text_Sign6, MSGBOX_SIGN
	end

SaffronCity_EventScript_GymSign::
	msgbox SaffronCity_Text_Sign7, MSGBOX_SIGN
	end

SaffronCity_EventScript_MrPsychicsHouseSign::
	msgbox SaffronCity_Text_Sign8, MSGBOX_SIGN
	end

SaffronCity_EventScript_TrainerFanClubSign::
	msgbox SaffronCity_Text_Sign9, MSGBOX_SIGN
	end

SaffronCity_Text_Sign1:
	.string "SaffronCity"

SaffronCity_Text_Sign2:
	.string "SaffronCity"

SaffronCity_Text_Sign3:
	.string "SaffronCity"

SaffronCity_Text_Sign4:
	.string "SaffronCity"

SaffronCity_Text_Sign5:
	.string "SaffronCity"

SaffronCity_Text_Sign6:
	.string "SaffronCity"

SaffronCity_Text_Sign7:
	.string "SaffronCity"

SaffronCity_Text_Sign8:
	.string "SaffronCity"

SaffronCity_Text_Sign9:
	.string "SaffronCity"

