PewterCity_MapScripts::
	.byte 0

PewterCity_EventScript_MuseumSign::
	msgbox PewterCity_Text_Sign1, MSGBOX_SIGN
	end

PewterCity_EventScript_PoliceNotice::
	msgbox PewterCity_Text_Sign2, MSGBOX_SIGN
	end

PewterCity_EventScript_GymSign::
	msgbox PewterCity_Text_Sign3, MSGBOX_SIGN
	end

PewterCity_EventScript_TrainerTips::
	msgbox PewterCity_Text_Sign4, MSGBOX_SIGN
	end

PewterCity_EventScript_CitySign::
	msgbox PewterCity_Text_Sign5, MSGBOX_SIGN
	end

PewterCity_Text_Sign1:
	.string "PewterCity"

PewterCity_Text_Sign2:
	.string "PewterCity"

PewterCity_Text_Sign3:
	.string "PewterCity"

PewterCity_Text_Sign4:
	.string "PewterCity"

PewterCity_Text_Sign5:
	.string "PewterCity"

