Route10_MapScripts::
	.byte 0

Route10_EventScript_SouthRockTunnelSign::
	msgbox Route10_Text_Sign1, MSGBOX_SIGN
	end

Route10_EventScript_PowerPlantSign::
	msgbox Route10_Text_Sign2, MSGBOX_SIGN
	end

Route10_EventScript_NorthRockTunnelSign::
	msgbox Route10_Text_Sign3, MSGBOX_SIGN
	end

Route10_Text_Sign1:
	.string "Route10"

Route10_Text_Sign2:
	.string "Route10"

Route10_Text_Sign3:
	.string "Route10"

