CeruleanCity_MapScripts::
	.byte 0

CeruleanCity_EventScript_CitySign::
	msgbox CeruleanCity_Text_Sign1, MSGBOX_SIGN
	end

CeruleanCity_EventScript_GymSign::
	msgbox CeruleanCity_Text_Sign2, MSGBOX_SIGN
	end

CeruleanCity_EventScript_BikeShopSign::
	msgbox CeruleanCity_Text_Sign3, MSGBOX_SIGN
	end

CeruleanCity_EventScript_TrainerTips::
	msgbox CeruleanCity_Text_Sign4, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle::
	msgbox CeruleanCity_Text_Sign5, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle::
	msgbox CeruleanCity_Text_Sign6, MSGBOX_SIGN
	end

CeruleanCity_BikeShop_EventScript_Bicycle::
	msgbox CeruleanCity_Text_Sign7, MSGBOX_SIGN
	end

CeruleanCity_Text_Sign1:
	.string "CeruleanCity"

CeruleanCity_Text_Sign2:
	.string "CeruleanCity"

CeruleanCity_Text_Sign3:
	.string "CeruleanCity"

CeruleanCity_Text_Sign4:
	.string "CeruleanCity"

CeruleanCity_Text_Sign5:
	.string "CeruleanCity"

CeruleanCity_Text_Sign6:
	.string "CeruleanCity"

CeruleanCity_Text_Sign7:
	.string "CeruleanCity"

