ViridianCity_MapScripts::
	.byte 0

ViridianCity_EventScript_TrainerTips1::
	msgbox ViridianCity_Text_Sign1, MSGBOX_SIGN
	end

ViridianCity_EventScript_GymSign::
	msgbox ViridianCity_Text_Sign2, MSGBOX_SIGN
	end

ViridianCity_EventScript_TrainerTips2::
	msgbox ViridianCity_Text_Sign3, MSGBOX_SIGN
	end

ViridianCity_EventScript_CitySign::
	msgbox ViridianCity_Text_Sign4, MSGBOX_SIGN
	end

ViridianCity_EventScript_GymDoor::
	msgbox ViridianCity_Text_Sign5, MSGBOX_SIGN
	end

ViridianCity_Text_Sign1:
	.string "ViridianCity"

ViridianCity_Text_Sign2:
	.string "ViridianCity"

ViridianCity_Text_Sign3:
	.string "ViridianCity"

ViridianCity_Text_Sign4:
	.string "ViridianCity"

ViridianCity_Text_Sign5:
	.string "ViridianCity"

