CeladonCity_MapScripts::
	.byte 0

CeladonCity_EventScript_TrainerTips2::
	msgbox CeladonCity_Text_Sign1, MSGBOX_SIGN
	end

CeladonCity_EventScript_PrizeExchangeSign::
	msgbox CeladonCity_Text_Sign2, MSGBOX_SIGN
	end

CeladonCity_EventScript_GameCornerSign::
	msgbox CeladonCity_Text_Sign3, MSGBOX_SIGN
	end

CeladonCity_EventScript_CitySign::
	msgbox CeladonCity_Text_Sign4, MSGBOX_SIGN
	end

CeladonCity_EventScript_MansionSign::
	msgbox CeladonCity_Text_Sign5, MSGBOX_SIGN
	end

CeladonCity_EventScript_TrainerTips1::
	msgbox CeladonCity_Text_Sign6, MSGBOX_SIGN
	end

CeladonCity_EventScript_DeptStoreSign::
	msgbox CeladonCity_Text_Sign7, MSGBOX_SIGN
	end

CeladonCity_EventScript_GymSign::
	msgbox CeladonCity_Text_Sign8, MSGBOX_SIGN
	end

CeladonCity_Text_Sign1:
	.string "CeladonCity"

CeladonCity_Text_Sign2:
	.string "CeladonCity"

CeladonCity_Text_Sign3:
	.string "CeladonCity"

CeladonCity_Text_Sign4:
	.string "CeladonCity"

CeladonCity_Text_Sign5:
	.string "CeladonCity"

CeladonCity_Text_Sign6:
	.string "CeladonCity"

CeladonCity_Text_Sign7:
	.string "CeladonCity"

CeladonCity_Text_Sign8:
	.string "CeladonCity"

